### ISSUE TITLE
using namespace std? 

### ISSUE THREAD

**Issue by Twenkid** [Anarcroth/process-scheduling-analysis#1]
Hi Martin,

Cool project! :)

Are you intentionally omitting the line:

`using namespace std `

Some kind of stylistic choice or reminder?

It would make all the std::string, std::vector etc. references optional.

Cheers! :) 

https://github.com/Anarcroth/process-scheduling-analysis/blob/20ca5e5dcc988c7aea1045c8ae6d25aac14a5dca/src/commons.cpp#L9

**Comment by Anarcroth** [comment]
Hi Todor. Thanks :)
Yes, I have a reason to omit the `std` namespace.
Without it, the code is clear which functions are coming from the standard set and which are my own. I am not poluting the global namespace this way.
Personally, I find the code more readable and clear of its intetions :)

**Comment by Twenkid** [comment]
Разбирам, допуснах че може би е така. :) Превключвам на български.

Честно казано и на мен понякога ми харесва като се посочва в дълги вериги
кое откъде идва, постоянно си подсказва и запомняш съдържанието на
пространствата.

Обаче за замърсяването  - с using според мен не се замърсява, просто
съкращава писането и редовете. (Да, може да забравиш от кое пространство е
функцията.)

Доколкото разгледах почти няма глобални неща освен main. Добра дисциплина и
модулност!

**Comment by Anarcroth** [comment]
Мерси :)
Честно казано се свиква с писането на `std::`, не е болка. А и има и autocompletion на текстовите редактори, което прави нещата поносими.
Иначе мерси за думите. Чувствай се свободен да тестваш :), въпреки че не се старая за кросплатформена поддръжка и сигурно ще гърмят неща наляво и надясно :sweat_smile:

**Comment by Twenkid** [comment]
За тестване чак не ми се занимава... То ще трябва и да се създаде подходяща
среда, да има смисъл, предполагам (не съм се задълбал в кода). Евентуално
ако е  част от система, която да го ползва.

**Comment by Anarcroth** [comment]
Това е само дипломна работа и трябва поне при мен да работи хаха. Иначе мерси че хвърли око :)

**Comment by Anarcroth** [comment]
>resolved
